version: '3'

services: 
    app:
        build: ./app # relative to the docker-compose file
        ports: 
            - 5000:80
        volumes: 
            - ./app:/app

    website:
        image: php:apache  
        volumes:
            - ./website:/var/www/html # mount
        ports:
            - 5001:80  # host:container
        links:
            - app  # website is not going to work unless app is running